#!/usr/bin/env python3
"""
A simple script to locate a specific server on your local network. So
your lazy self doesn't need to connect to it manually.

It reports the global and local connection. The tool was created so I could
bring around a machine that doesn't have a screen or keyboard but can be
plugged in and out of a few known networks without setup. This allows
me to securely discover what ip that machine is so I can ssh into it.
"""

import os
import sys
import json
import click
import base64
import netifaces
import getpass
import requests
from github import Github, InputFileContent
from cryptography.hazmat.backends import default_backend
from cryptography.fernet import Fernet
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import padding


def encrypt(plaintext, public_key):
    key = Fernet.generate_key()

    # Wrap the key in the public
    wrapped_key = public_key.encrypt(
        key,
        padding.OAEP(
            mgf=padding.MGF1(algorithm=hashes.SHA256()),
            algorithm=hashes.SHA256(),
            label=None,
        )
    )

    f = Fernet(key)
    token = f.encrypt(str.encode(plaintext))

    return json.dumps({
        "token": token.decode(),
        "wrapped_key": base64.b64encode(wrapped_key).decode(),
    })


def decrypt(raw_payload, private_key):
    payload = json.loads(raw_payload)

    unwrapped_key = private_key.decrypt(
        base64.b64decode(payload['wrapped_key']),
        padding.OAEP(
            mgf=padding.MGF1(algorithm=hashes.SHA256()),
            algorithm=hashes.SHA256(),
            label=None,
        )
    )

    f = Fernet(unwrapped_key.decode())

    plaintext_bytes = f.decrypt(str.encode(payload['token']))
    return plaintext_bytes.decode()


def matches_cache(cache_file, ips_str):
    if not os.path.exists(cache_file):
        return False

    if open(cache_file).read() == ips_str:
        return True
    return False


@click.group()
def cli():
    pass


@cli.command()
@click.option('--config-path', default='/etc/whereareyou/config.json', help='Path to config file')
@click.option('--gh-token', help='Github token to use')
@click.option('--gh-gist-id', help='Gist id to update')
@click.option('--gh-gist-file-name', help='Gist file name to update')
@click.option('--public-key-path', help='Public key to encrypt the message')
def announce(config_path, gh_token, gh_gist_id, gh_gist_file_name, public_key_path):
    config = {}
    if os.path.exists(config_path):
        config = json.load(open(config_path))
    elif os.path.exists('config.json'):
        config = json.load(open('config.json'))
    cache_file = config.setdefault('cache_file', '.localcache')

    if not gh_token:
        gh_token = config.get('gh_token')
        if not gh_token:
            print("Need a github token to continue")
            sys.exit(1)

    if not gh_gist_id:
        gh_gist_id = config.get('gh_gist_id')
        if not gh_gist_id:
            print("Need a github gist id to continue")
            sys.exit(1)

    if not gh_gist_file_name:
        gh_gist_file_name = config.get('gh_gist_file_name')
        if not gh_gist_file_name:
            print("Need a github gist filename to continue")
            sys.exit(1)

    if not public_key_path:
        public_key_path = config.get('public_key_path')
        if not public_key_path:
            print("Need a public key path to continue")
            sys.exit(1)

    ips = []

    interfaces = netifaces.interfaces()

    for interface in interfaces:
        ifaddresses = netifaces.ifaddresses(interface)

        ipv4_setup = ifaddresses.get(netifaces.AF_INET, [])
        for ipv4 in ipv4_setup:
            ip = ipv4.get('addr', None)
            if not ip:
                continue
            ips.append(ip)

    # Sort ips so we can compare the cache
    ips.sort()

    ips_str = "\n".join(ips)

    try:
        current_global_ip = requests.get("https://api.ipify.org").text
    except:
        print("Problems getting global ip")
        current_global_ip = ""

    ips_report = "global:\n%s\n\nlan:\n%s" % (current_global_ip, ips_str)

    # Compare the cache
    if matches_cache(cache_file, ips_report):
        print("Nothing has changed since the last update. Do nothing.")
        sys.exit(0)

    g = Github(gh_token)

    gist = g.get_gist(gh_gist_id)

    public_key = serialization.load_ssh_public_key(
        str.encode(open(public_key_path).read()),
        backend=default_backend(),
    )

    file_content = encrypt(ips_report, public_key)

    gist.edit(files={
        gh_gist_file_name: InputFileContent(content=file_content),
    })

    # Save cache
    cache = open(cache_file, 'w')
    cache.write(ips_report)
    cache.close()

    print("Successfully announced location on github")


@cli.command()
@click.option('--config_path', default='/etc/whereareyou/config.json', help='path to the json config file')
@click.option('--gh-token', help='Github token to use')
@click.option('--gh-gist-id', help='Gist id to update')
@click.option('--gh-gist-file-name', help='Gist file name to update')
@click.option('--prompt-for-passphrase/--no-prompt-for-passphrase', default=False, help='prompt for a passphrase')
@click.option('--private-key-path', help='Public key to encrypt the message')
def locate(config_path, gh_token, gh_gist_id, gh_gist_file_name, prompt_for_passphrase, private_key_path):
    config = {}
    if os.path.exists(config_path):
        config = json.load(open(config_path))
    # Try a local config if it's there
    elif os.path.exists('config.json'):
        config = json.load(open('config.json'))

    if not gh_token:
        gh_token = config.get('gh_token')
        if not gh_token:
            print("Need a github token to continue")
            sys.exit(1)

    if not gh_gist_id:
        gh_gist_id = config.get('gh_gist_id')
        if not gh_gist_id:
            print("Need a github gist id to continue")
            sys.exit(1)

    if not gh_gist_file_name:
        gh_gist_file_name = config.get('gh_gist_file_name')
        if not gh_gist_file_name:
            print("Need a github gist filename to continue")
            sys.exit(1)

    if not private_key_path:
        private_key_path = config.get('private_key_path')
        if not private_key_path:
            print("Need a public key path to continue")
            sys.exit(1)

    g = Github(gh_token)

    gist = g.get_gist(gh_gist_id)

    gist_file = gist.files[gh_gist_file_name]

    private_key_password = None
    if prompt_for_passphrase:
        private_key_password = str.encode(
            getpass.getpass("Private key passphrase:"))

    private_key = serialization.load_pem_private_key(
        str.encode(open(private_key_path).read()),
        password=private_key_password,
        backend=default_backend(),
    )

    print(decrypt(gist_file.content, private_key))


if __name__ == '__main__':
    cli()
